services:
  - type: web
    name: invoice-backend
    env: node
    root: layoutgenrates
    buildCommand: npm install
    startCommand: node index.js
    plan: free
    buildpacks:
      - key: https://github.com/puppeteer/puppeteer-buildpack.git